name: cuidapet_shelf
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.5.0
  crypto: ^3.0.5
  dotenv: ^3.0.0  
  # dotenv: ^4.2.0 # não funciona, conflito com o ENV
  get_it: ^7.7.0
  # http_parser: ^4.1.0
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  jaguar_jwt: ^3.0.0
  logger: ^2.4.0
  mysql1: ^0.20.0
  shelf: ^1.4.2
  collection: ^1.19.0
  http_parser: ^4.1.0
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0
    # git: 
      # url: endereço no git
      # path: nome da pasta

dev_dependencies:
  build_runner: ^2.4.12
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.25.8

# para quando necessário sobescrever
# dependencies_overrrides
#